/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EpCirclePlusFilled: typeof import('~icons/ep/circle-plus-filled')['default']
    EpFullScreen: typeof import('~icons/ep/full-screen')['default']
    EpHeadset: typeof import('~icons/ep/headset')['default']
    EpKey: typeof import('~icons/ep/key')['default']
    EpPlay: typeof import('~icons/ep/play')['default']
    EpQrCode: typeof import('~icons/ep/qr-code')['default']
    EpSearch: typeof import('~icons/ep/search')['default']
    EpShield: typeof import('~icons/ep/shield')['default']
    EpUser: typeof import('~icons/ep/user')['default']
    EpUserPlus: typeof import('~icons/ep/user-plus')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconEpCheck: typeof import('~icons/ep/check')['default']
    IconEpClose: typeof import('~icons/ep/close')['default']
    IconEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IconEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
