/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    EpExpand: typeof import('~icons/ep/expand')['default']
    EpHeadset: typeof import('~icons/ep/headset')['default']
    EpSearch: typeof import('~icons/ep/search')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MdiArrowDownBold: typeof import('~icons/mdi/arrow-down-bold')['default']
    MdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    MdiDownload: typeof import('~icons/mdi/download')['default']
    MdiHeadphones: typeof import('~icons/mdi/headphones')['default']
    MdiHeart: typeof import('~icons/mdi/heart')['default']
    MdiHeartOutline: typeof import('~icons/mdi/heart-outline')['default']
    MdiPause: typeof import('~icons/mdi/pause')['default']
    MdiPlay: typeof import('~icons/mdi/play')['default']
    MdiPlusThick: typeof import('~icons/mdi/plus-thick')['default']
    MdiRepeat: typeof import('~icons/mdi/repeat')['default']
    MdiRepeatOnce: typeof import('~icons/mdi/repeat-once')['default']
    MdiShare: typeof import('~icons/mdi/share')['default']
    MdiShuffleVariant: typeof import('~icons/mdi/shuffle-variant')['default']
    MdiSkipNext: typeof import('~icons/mdi/skip-next')['default']
    MdiSkipPrevious: typeof import('~icons/mdi/skip-previous')['default']
    MdiStar: typeof import('~icons/mdi/star')['default']
    MdiStarOutline: typeof import('~icons/mdi/star-outline')['default']
    MdiThumbUp: typeof import('~icons/mdi/thumb-up')['default']
    MdiThumbUpOutline: typeof import('~icons/mdi/thumb-up-outline')['default']
    MdiYoutube: typeof import('~icons/mdi/youtube')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
